# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7288ad4304d6888a91223c80ff7f81baa703948deb16b0e7fe20c3213a345538e9bc7ab5f5c6d1fa05db707a98e9191ee9ab2488c6b894fbd83773c864c22a

test:
  secret_key_base: 485998f648ec4f0db63ab06c7fa7e91beecae8eca78b55736ae36fcb43795af01ab42350da70e1f179067f4253df3153108ba2a30b8d0b2341620084beae5e94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
